/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ay23man (https://sketchfab.com/ay23man)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/satellites-1dfb3bb50daa4f6f94fdcad1321ce50f
Title: Satellites
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

// --- CHANGE 1: RENAMED 'Tractor' TO 'Satellite' ---
export function Tractor(props) {
  const { nodes, materials } = useGLTF('/models/satellite.glb')

  // --- CHANGE 2: CREATE BRIGHT VERSIONS FOR EACH MATERIAL ---
  const brightMaterial1 = (
    <meshStandardMaterial 
      color="white"           // Force the base color to be white and bright
      emissive="white"        // Add a white glow
      emissiveIntensity={0.5}   // Increase the glow intensity significantly
      metalness={0.5}           // Reduce metalness to make it less dark in shadows
      roughness={0.5}           // Adjust roughness for a nice sheen
    />
  );


  const brightMaterial2 = (
    <meshStandardMaterial 
      {...materials['Course_Satellites_-_1_Texture']}
      emissive="white"
      emissiveIntensity={0.15}
    />
  );
  const brightMaterial3 = (
    <meshStandardMaterial 
      {...materials['Course_Satellites_-_1_Mtl']}
      emissive="white"
      emissiveIntensity={0.15}
    />
  );

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[104.258, -130.377, 1.447]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          
          {/* --- CHANGE 3: APPLY THE NEW MATERIALS --- */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Course_Satellites_Model_Course_Satellites_-_2_Mtl_0'].geometry}>
            {brightMaterial1}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Course_Satellites_Model_Course_Satellites_-_1_Texture_0'].geometry}>
            {brightMaterial2}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Course_Satellites_Model_Course_Satellites_-_1_Mtl_0'].geometry}>
            {brightMaterial3}
          </mesh>

        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/satellite.glb')