/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MartianDays (https://sketchfab.com/MartianDays)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spacex-starship-a8a0b69f776841a1a465cd9fb3762fd2
Title: SpaceX Starship
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

// The component has been renamed to 'Starship'
export function Starship(props) {
  // The path has been corrected to '/models/starship.glb'
  const { nodes, materials } = useGLTF('/models/starship.glb')

  // We create one bright material, since all parts use the same original material
  const brightMaterial = (
    <meshStandardMaterial          // Force the base color to be white and bright     // Add a white glow
      emissiveIntensity={0.5}   // Increase the glow intensity significantly
      metalness={0.5}           // Reduce metalness to make it less dark in shadows
      roughness={0.5}           // Adjust roughness for a nice sheen
    />
  );



  return (
    <group {...props} dispose={null}>
      <group position={[0, -5293.177, -42.376]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          
          {/* The new brightMaterial is applied as a child to each mesh */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bow_Window001_Starship_0.geometry}
            rotation={[0, 0, Math.PI / 2]}
            scale={100}>
            {brightMaterial}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Primary_Hull001_Starship_0.geometry}
            rotation={[0, 0, Math.PI / 2]}
            scale={100}>
            {brightMaterial}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cargo_Doors001_Starship_0.geometry}
            rotation={[0, 0, Math.PI / 2]}
            scale={100}>
            {brightMaterial}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SeaLev_Raptors_LP001_Starship_0.geometry}
            position={[0, 0, 123.114]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[65.532, 65.532, 81.725]}>
            {brightMaterial}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vacuum_Raptors_LP001_Starship_0.geometry}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[65.532, 65.532, 81.725]}>
            {brightMaterial}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cargo_DropBoxes001_Starship_0.geometry}
            position={[-1.126, -0.26, 0]}
            rotation={[0, 0, -Math.PI / 6]}
            scale={100}>
            {brightMaterial}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabin_WindowInset001_Starship_0.geometry}
            rotation={[0, 0, Math.PI / 2]}
            scale={100}>
            {brightMaterial}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabin_Windows001_Starship_0.geometry}
            rotation={[0, 0, Math.PI / 2]}
            scale={100}>
            {brightMaterial}
          </mesh>
          
        </group>
      </group>
    </group>
  )
}

// The preload path has also been corrected
useGLTF.preload('/models/starship.glb')